cat > docker-compose.yml <<'YML'
services:
  db:
    image: timescale/timescaledb:latest-pg15
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
YML